export const GHOST             = '#ced4da'
export const  WHITE            = '#ffffff'
export const  WHITE_ALT        = '#f5f5f5'
export const  BLACK_LIGHT      = '#4a4a4a'
export const  BLACK            = '#333333'
export const  BLACK_ALL        = '#000000'
export const  GRAY_LIGHT       = '#d1d1d1'
export const  GRAY_ALT         = '#eeeeee'
export const  GRAY             = '#b6b6b6'
export const  GRAY_10          = '#727272'
export const  GRAY_DARK        = '#4c4c4c'
export const  GRAY_DARK_75     = '#989898'
export const  GRAY_DARK_ALT    = '#8c8c8c'
export const  MERCURY          = '#e3e3e3'

export const  BLUE             = '#5ca0d3'
export const  YELLOW           = '#fcd307'
export const  ORANGE           = '#FFB74D'
export const  DEEP             = '#2c3848'
export const  DEEPBLACK        = '#5b616b'
export const  RED              = '#d3211f'
export const  GREEN            = '#4caf50'
export const  EBONY            = '#12162b'
export const  BIGSTONE         = '#19223c'

export const  OSLO_GRAY        = '#8b959a'
export const  BLUE_2           = '#0857ab'
export const  YELLOW_25        = '#ffc72a'

export const  OPACITY_MODAL    = 'rgba(0, 0, 0, 0.5)'
export const  OPACITY_LIGHT    = 'rgba(0, 0, 0, 0.1)'
export const  OPACITY_3        = 'rgba(0, 0, 0, 0.3)'